// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1p4VGXNIAPFmYNxNnKxQu4RkBgIotAy8',
    appId: '1:117119675056:web:c6dfae20f45ec4f8a76975',
    messagingSenderId: '117119675056',
    projectId: 'login-3d3ad',
    authDomain: 'login-3d3ad.firebaseapp.com',
    storageBucket: 'login-3d3ad.appspot.com',
    measurementId: 'G-CRBSDLP4YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdJWfFI8l0FGlZfBE2RlCrk0NAxQ-tJI',
    appId: '1:117119675056:android:639d72521f22ac16a76975',
    messagingSenderId: '117119675056',
    projectId: 'login-3d3ad',
    storageBucket: 'login-3d3ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZrU4L21d8E0vZttq7fFRuBiQ7P380nc',
    appId: '1:117119675056:ios:fa7817f67855035aa76975',
    messagingSenderId: '117119675056',
    projectId: 'login-3d3ad',
    storageBucket: 'login-3d3ad.appspot.com',
    androidClientId: '117119675056-2jbvn5lo4v40595s9fhmqja6uags5h75.apps.googleusercontent.com',
    iosClientId: '117119675056-g4e25o94j6n3s29p781gjf9ue8th5eer.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

}